#!/usr/bin/env python
# encoding: utf-8

name = "seed"
shortDesc = ""
longDesc = """

"""
autoGenerated=True
entry(
    index = 0,
    label = "H + H <=> H2",
    degeneracy = 0.5,
    duplicate = True,
    kinetics = Arrhenius(A=(5.45e+10,'cm^3/(mol*s)'), n=0, Ea=(6.276,'kJ/mol'), T0=(1,'K'), Tmin=(278,'K'), Tmax=(372,'K'), comment="""Matched reaction 56 H + H <=> H2 in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 56 H + H <=> H2 in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
family: R_Recombination
""",
)

entry(
    index = 1,
    label = "H + H <=> H2",
    degeneracy = 0.5,
    duplicate = True,
    kinetics = Arrhenius(A=(5.45e+10,'cm^3/(mol*s)'), n=0, Ea=(6.276,'kJ/mol'), T0=(1,'K'), Tmin=(278,'K'), Tmax=(372,'K'), comment="""Matched reaction 56 H + H <=> H2 in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 56 H + H <=> H2 in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_2CHNO->H]
family: R_Recombination
""",
)

entry(
    index = 2,
    label = "H + [CH]=O <=> H2 + CO",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(9.03e+13,'cm^3/(mol*s)','*|/',2), n=0, Ea=(11023.1,'cal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 0 HCO + H <=> CO + H2 in CO_Disproportionation/training
    This reaction matched rate rule [H_rad;HCO]
    family: CO_Disproportionation
    Ea raised from 0.0 to 46.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 0 HCO + H <=> CO + H2 in CO_Disproportionation/training
This reaction matched rate rule [H_rad;HCO]
family: CO_Disproportionation
Ea raised from 0.0 to 46.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 3,
    label = "H + CO <=> [CH]=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.18e+11,'cm^3/(mol*s)'), n=0, Ea=(11.3805,'kJ/mol'), T0=(1,'K'), Tmin=(345,'K'), Tmax=(449,'K'), comment="""Matched reaction 4 H + CO <=> CHO in R_Addition_COm/training
    This reaction matched rate rule [COm;H_rad]
    family: R_Addition_COm"""),
    longDesc = 
"""
Matched reaction 4 H + CO <=> CHO in R_Addition_COm/training
This reaction matched rate rule [COm;H_rad]
family: R_Addition_COm
""",
)

entry(
    index = 4,
    label = "H + [CH]=O <=> H2 + CO",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(9.03e+13,'cm^3/(mol*s)','*|/',2), n=0, Ea=(11023.1,'cal/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 0 HCO + H <=> CO + H2 in CO_Disproportionation/training
    This reaction matched rate rule [H_rad;HCO]
    family: CO_Disproportionation
    Ea raised from 0.0 to 46.1 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 0 HCO + H <=> CO + H2 in CO_Disproportionation/training
This reaction matched rate rule [H_rad;HCO]
family: CO_Disproportionation
Ea raised from 0.0 to 46.1 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 5,
    label = "[CH]=O + [CH]=O <=> O=CC=O",
    degeneracy = 0.5,
    kinetics = Arrhenius(A=(7.55e+12,'cm^3/(mol*s)','+|-',6.02e+12), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), comment="""Matched reaction 93 CHO + CHO <=> C2H2O2 in R_Recombination/training
    This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_N-Sp-3R!H-2R_3R!H->O_Ext-1C-R_N-4R!H->C]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 93 CHO + CHO <=> C2H2O2 in R_Recombination/training
This reaction matched rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_N-Sp-3R!H-2R_3R!H->O_Ext-1C-R_N-4R!H->C]
family: R_Recombination
""",
)

entry(
    index = 6,
    label = "CO + [CH]=O <=> O=[C]C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1614.82,'m^3/(mol*s)'), n=0.595184, Ea=(5.28251,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [COm;Y_rad] for rate rule [COm;CO_pri_rad]
    Euclidian distance = 2.0
    family: R_Addition_COm"""),
    longDesc = 
"""
Estimated using template [COm;Y_rad] for rate rule [COm;CO_pri_rad]
Euclidian distance = 2.0
family: R_Addition_COm
""",
)

entry(
    index = 7,
    label = "H + O=[C]C=O <=> O=CC=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.10287e+13,'m^3/(mol*s)'), n=-2.74437, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O',), comment="""BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O
        Total Standard Deviation in ln(k): 11.5401827615
    Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O]
    Euclidian distance = 0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O
    Total Standard Deviation in ln(k): 11.5401827615
Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 8,
    label = "[CH]=O + O=[C]C=O <=> CO + O=CC=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.8e+13,'cm^3/(mol*s)','+|-',9e+12), n=0, Ea=(111.858,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CO_rad;HCO] for rate rule [CO_rad/OneDe;HCO]
    Euclidian distance = 2.0
    family: CO_Disproportionation
    Ea raised from 0.0 to 111.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [CO_rad;HCO] for rate rule [CO_rad/OneDe;HCO]
Euclidian distance = 2.0
family: CO_Disproportionation
Ea raised from 0.0 to 111.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 9,
    label = "H + O=CC=O <=> H2 + O=[C]C=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(260000,'cm^3/(mol*s)'), n=2.58, Ea=(5.1003,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CO_sec;H_rad] for rate rule [CO/H/OneDe;H_rad]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [CO_sec;H_rad] for rate rule [CO/H/OneDe;H_rad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 10,
    label = "H2 + CO <=> C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.89e+09,'cm^3/(mol*s)'), n=1.16, Ea=(343.506,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Matched reaction 2 H2 + CO <=> CH2O in 1,2_Insertion_CO/training
    This reaction matched rate rule [CO;H2]
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Matched reaction 2 H2 + CO <=> CH2O in 1,2_Insertion_CO/training
This reaction matched rate rule [CO;H2]
family: 1,2_Insertion_CO
""",
)

entry(
    index = 11,
    label = "H2 + [CH]=O <=> H + C=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.8e+06,'cm^3/(mol*s)','*|/',5), n=2, Ea=(204.765,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Matched reaction 309 H2 + HCO_r3 <=> CH2O + H in H_Abstraction/training
    This reaction matched rate rule [H2;CO_pri_rad]
    family: H_Abstraction"""),
    longDesc = 
"""
Matched reaction 309 H2 + HCO_r3 <=> CH2O + H in H_Abstraction/training
This reaction matched rate rule [H2;CO_pri_rad]
family: H_Abstraction
""",
)

entry(
    index = 12,
    label = "H + [CH]=O <=> C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.68e+10,'cm^3/(mol*s)'), n=0, Ea=(-18.9535,'kJ/mol'), T0=(1,'K'), Tmin=(1500,'K'), Tmax=(1900,'K'), comment="""Matched reaction 63 H + CHO <=> CH2O in R_Recombination/training
    This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O]
    family: R_Recombination"""),
    longDesc = 
"""
Matched reaction 63 H + CHO <=> CH2O in R_Recombination/training
This reaction matched rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O]
family: R_Recombination
""",
)

entry(
    index = 13,
    label = "[CH]=O + [CH]=O <=> CO + C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.8e+13,'cm^3/(mol*s)','+|-',9e+12), n=0, Ea=(27380.2,'cal/mol'), T0=(1,'K'), comment="""Matched reaction 5 HCO + HCO_Y <=> CO + CH2O in CO_Disproportionation/training
    This reaction matched rate rule [CO_pri_rad;HCO]
    family: CO_Disproportionation
    Ea raised from 0.0 to 114.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Matched reaction 5 HCO + HCO_Y <=> CO + CH2O in CO_Disproportionation/training
This reaction matched rate rule [CO_pri_rad;HCO]
family: CO_Disproportionation
Ea raised from 0.0 to 114.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 14,
    label = "C=O + O=[C]C=O <=> [CH]=O + O=CC=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.81e+11,'cm^3/(mol*s)','*|/',10), n=0, Ea=(54.0573,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Estimated using template [CO_pri;CO_sec_rad] for rate rule [CO_pri;CO_rad/OneDe]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [CO_pri;CO_sec_rad] for rate rule [CO_pri;CO_rad/OneDe]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 15,
    label = "H + OCCO <=> O=[C]C=O",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.82057e+14,'m^3/(mol*s)'), n=-2.74437, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O',), comment="""BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O
        Total Standard Deviation in ln(k): 11.5401827615
    Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O
    Total Standard Deviation in ln(k): 11.5401827615
Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 16,
    label = "[CH]=O + OCCO <=> CO + O=[C]C=O",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(2.6953e+09,'m^3/(mol*s)'), n=-0.548333, Ea=(188.901,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Y_rad;HCO]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: CO_Disproportionation
    Ea raised from 187.9 to 188.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using an average for rate rule [Y_rad;HCO]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: CO_Disproportionation
Ea raised from 187.9 to 188.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 17,
    label = "H + OCCO <=> O=[C]C=O",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.82057e+14,'m^3/(mol*s)'), n=-2.74437, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O',), comment="""BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O
        Total Standard Deviation in ln(k): 11.5401827615
    Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O
    Total Standard Deviation in ln(k): 11.5401827615
Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 18,
    label = "[CH]=O + OCCO <=> CO + O=[C]C=O",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(2.6953e+09,'m^3/(mol*s)'), n=-0.548333, Ea=(188.901,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Y_rad;HCO]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: CO_Disproportionation
    Ea raised from 187.9 to 188.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using an average for rate rule [Y_rad;HCO]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: CO_Disproportionation
Ea raised from 187.9 to 188.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 19,
    label = "H + OCCO(S) <=> O=[C]C=O",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.246e+09,'cm^3/(mol*s)'), n=1.429, Ea=(16.6816,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Cdd_Cdd;HJ] for rate rule [Ck_Ck;HJ]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Estimated using template [Cdd_Cdd;HJ] for rate rule [Ck_Ck;HJ]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: R_Addition_MultipleBond
""",
)

entry(
    index = 20,
    label = "H + O=[C]C=O <=> H2 + OCCO(S)",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(115717,'m^3/(mol*s)'), n=0.55, Ea=(0.0976267,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [H_rad;XH_s_Rrad] for rate rule [H_rad;COpri_COrad]
    Euclidian distance = 2.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [H_rad;XH_s_Rrad] for rate rule [H_rad;COpri_COrad]
Euclidian distance = 2.0
family: Disproportionation
""",
)

entry(
    index = 21,
    label = "[CH]=O + O=[C]C=O <=> C=O + OCCO(S)",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.81e+14,'cm^3/(mol*s)','*|/',3), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Estimated using template [CO_pri_rad;XH_s_Rrad] for rate rule [CO_pri_rad;COpri_COrad]
    Euclidian distance = 2.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [CO_pri_rad;XH_s_Rrad] for rate rule [CO_pri_rad;COpri_COrad]
Euclidian distance = 2.0
family: Disproportionation
""",
)

entry(
    index = 22,
    label = "O=[C]C=O + O=[C]C=O <=> OCCO(S) + O=CC=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.81e+08,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CO_rad;XH_s_Rrad] for rate rule [CO_rad/OneDe;COpri_COrad]
    Euclidian distance = 2.8284271247461903
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [CO_rad;XH_s_Rrad] for rate rule [CO_rad/OneDe;COpri_COrad]
Euclidian distance = 2.8284271247461903
family: Disproportionation
""",
)

entry(
    index = 23,
    label = "OCCO => OCCO(S)",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(1e+10,'s^-1'), n=0, Ea=(54.1739,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [NOS]
    Euclidian distance = 0
    family: 1,2-Birad_to_alkene
    Ea raised from 0.0 to 54.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using an average for rate rule [NOS]
Euclidian distance = 0
family: 1,2-Birad_to_alkene
Ea raised from 0.0 to 54.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 24,
    label = "OCCO + O=[C]C=O <=> OCCO(S) + O=[C]C=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(132201,'m^3/(mol*s)'), n=0.573402, Ea=(54.1739,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Y_rad;XH_s_Rrad] for rate rule [Y_rad;COpri_COrad]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Disproportionation
    Ea raised from 53.2 to 54.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Y_rad;XH_s_Rrad] for rate rule [Y_rad;COpri_COrad]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
Ea raised from 53.2 to 54.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 25,
    label = "H + OCCO(S) <=> O=[C]C=O",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = Arrhenius(A=(14097,'m^3/(mol*s)'), n=1.43107, Ea=(2.92155,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""From training reaction 188 used for Ck_O;HJ
    Exact match found for rate rule [Ck_O;HJ]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
From training reaction 188 used for Ck_O;HJ
Exact match found for rate rule [Ck_O;HJ]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Addition_MultipleBond
""",
)

entry(
    index = 26,
    label = "vacantX + vacantX + H2 <=> [Pt] + [Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 27,
    label = "vacantX + H <=> [Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 28,
    label = "H + [O]C=C[O] <=> H2 + O=[C]C=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(6.96062e+06,'m^3/(mol*s)'), n=0, Ea=(25.104,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Y_rad;Cdpri_Rrad] for rate rule [H_rad;Cdpri_Orad]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [Y_rad;Cdpri_Rrad] for rate rule [H_rad;Cdpri_Orad]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 29,
    label = "H + O=[C]C=O <=> [O]C=C[O]",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7048.5,'m^3/(mol*s)'), n=1.43107, Ea=(2.92155,'kJ/mol'), T0=(1,'K'), Tmin=(303.03,'K'), Tmax=(2000,'K'), comment="""From training reaction 188 used for Ck_O;HJ
    Exact match found for rate rule [Ck_O;HJ]
    Euclidian distance = 0
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
From training reaction 188 used for Ck_O;HJ
Exact match found for rate rule [Ck_O;HJ]
Euclidian distance = 0
family: R_Addition_MultipleBond
""",
)

entry(
    index = 30,
    label = "O=[C]C=O + [O]C=C[O] <=> O=[C]C=O + O=CC=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.62e+08,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CO_rad;XH_s_Rrad] for rate rule [CO_rad/OneDe;Cdpri_Orad]
    Euclidian distance = 2.8284271247461903
    Multiplied by reaction path degeneracy 2.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [CO_rad;XH_s_Rrad] for rate rule [CO_rad/OneDe;Cdpri_Orad]
Euclidian distance = 2.8284271247461903
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 31,
    label = "OCCO + [O]C=C[O] <=> O=[C]C=O + O=[C]C=O",
    degeneracy = 4.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.39212e+07,'m^3/(mol*s)'), n=0, Ea=(25.104,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Y_rad;Cdpri_Rrad] for rate rule [Y_rad;Cdpri_Orad]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 4.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [Y_rad;Cdpri_Rrad] for rate rule [Y_rad;Cdpri_Orad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: Disproportionation
""",
)

entry(
    index = 32,
    label = "[CH]=O + [O]C=C[O] <=> C=O + O=[C]C=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.62e+14,'cm^3/(mol*s)','*|/',3), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Estimated using template [CO_pri_rad;XH_s_Rrad] for rate rule [CO_pri_rad;Cdpri_Orad]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [CO_pri_rad;XH_s_Rrad] for rate rule [CO_pri_rad;Cdpri_Orad]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 33,
    label = "[O]C=C[O] => O=CC=O",
    degeneracy = 1.0,
    reversible = False,
    kinetics = Arrhenius(A=(1e+10,'s^-1'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [NOS]
    Euclidian distance = 0
    family: 1,2-Birad_to_alkene"""),
    longDesc = 
"""
Estimated using an average for rate rule [NOS]
Euclidian distance = 0
family: 1,2-Birad_to_alkene
""",
)

entry(
    index = 34,
    label = "OCCO + [O]C=C[O] <=> O=[C]C=O + O=[C]C=O",
    degeneracy = 4.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.39212e+07,'m^3/(mol*s)'), n=0, Ea=(25.104,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Y_rad;Cdpri_Rrad] for rate rule [Y_rad;Cdpri_Orad]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 4.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [Y_rad;Cdpri_Rrad] for rate rule [Y_rad;Cdpri_Orad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 4.0
family: Disproportionation
""",
)

entry(
    index = 35,
    label = "[O][C]=C[O] <=> O=[C]C=O",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.949e+11,'s^-1'), n=0.486, Ea=(22.8614,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [R2radExo;Y_rad;XH_Rrad]
    Euclidian distance = 0
    family: Intra_Disproportionation"""),
    longDesc = 
"""
Estimated using an average for rate rule [R2radExo;Y_rad;XH_Rrad]
Euclidian distance = 0
family: Intra_Disproportionation
""",
)

entry(
    index = 36,
    label = "H + [O][C]=C[O] <=> H2 + OCCO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(339.411,'m^3/(mol*s)'), n=1.5, Ea=(-3.72376,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [H_rad;CH_d_Rrad]
    Euclidian distance = 0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using an average for rate rule [H_rad;CH_d_Rrad]
Euclidian distance = 0
family: Disproportionation
""",
)

entry(
    index = 37,
    label = "H + OCCO <=> [O][C]=C[O]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(8556.54,'m^3/(mol*s)'), n=1.383, Ea=(15.1097,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Ct_Ct;HJ]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Estimated using an average for rate rule [Ct_Ct;HJ]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Addition_MultipleBond
""",
)

entry(
    index = 38,
    label = "O=[C]C=O + [O][C]=C[O] <=> OCCO + O=CC=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.81e+08,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CO_rad;XH_Rrad] for rate rule [CO_rad/OneDe;CH_d_Rrad]
    Euclidian distance = 2.8284271247461903
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [CO_rad;XH_Rrad] for rate rule [CO_rad/OneDe;CH_d_Rrad]
Euclidian distance = 2.8284271247461903
family: Disproportionation
""",
)

entry(
    index = 39,
    label = "OCCO + [O][C]=C[O] <=> OCCO + O=[C]C=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(8.60204,'m^3/(mol*s)'), n=1.90834, Ea=(-4.74649,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Y_rad;CH_d_Rrad]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using an average for rate rule [Y_rad;CH_d_Rrad]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 40,
    label = "[CH]=O + [O][C]=C[O] <=> C=O + OCCO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(27901.3,'m^3/(mol*s)'), n=0.954172, Ea=(-2.37324,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [Y_rad;CH_d_Rrad] + [CO_pri_rad;XH_Rrad] for rate rule [CO_pri_rad;CH_d_Rrad]
    Euclidian distance = 2.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using average of templates [Y_rad;CH_d_Rrad] + [CO_pri_rad;XH_Rrad] for rate rule [CO_pri_rad;CH_d_Rrad]
Euclidian distance = 2.0
family: Disproportionation
""",
)

entry(
    index = 41,
    label = "H + [O][C]=C[O] <=> [O]C=C[O]",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(8.15666e+12,'m^3/(mol*s)'), n=-1.49308, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.399348053434, var=9.35827249741, Tref=1000.0, N=6, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_N-3R!H->O',), comment="""BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_N-3R!H->O
        Total Standard Deviation in ln(k): 7.13613102162
    Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_N-3R!H->O]
    Euclidian distance = 0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_N-3R!H->O
    Total Standard Deviation in ln(k): 7.13613102162
Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_N-3R!H->O]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 42,
    label = "[CH]=O + [O][C]=C[O] <=> CO + [O]C=C[O]",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.34765e+09,'m^3/(mol*s)'), n=-0.548333, Ea=(27.145,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Y_rad;HCO]
    Euclidian distance = 0
    family: CO_Disproportionation"""),
    longDesc = 
"""
Estimated using an average for rate rule [Y_rad;HCO]
Euclidian distance = 0
family: CO_Disproportionation
""",
)

entry(
    index = 43,
    label = "H2 + [O][C]=C[O] <=> H + [O]C=C[O]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(231776,'m^3/(mol*s)'), n=0.75, Ea=(89.2238,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [H2;Y_1centerbirad]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using an average for rate rule [H2;Y_1centerbirad]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 44,
    label = "C=O + [O][C]=C[O] <=> [CH]=O + [O]C=C[O]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(50126.2,'m^3/(mol*s)'), n=0.285, Ea=(5.7739,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [CO_pri;Y_1centerbirad]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using an average for rate rule [CO_pri;Y_1centerbirad]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 45,
    label = "[O][C]=C[O] + O=CC=O <=> O=[C]C=O + [O]C=C[O]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.16e+07,'m^3/(mol*s)'), n=0, Ea=(7.56467,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CO_sec;Y_1centerbirad] for rate rule [CO/H/OneDe;Y_1centerbirad]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [CO_sec;Y_1centerbirad] for rate rule [CO/H/OneDe;Y_1centerbirad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 46,
    label = "[O][C]=C[O] + [O]C=C[O] <=> O=[C]C=O + [O]C=C[O]",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(6.96062e+06,'m^3/(mol*s)'), n=0, Ea=(25.104,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Y_rad;Cdpri_Rrad] for rate rule [Y_rad;Cdpri_Orad]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [Y_rad;Cdpri_Rrad] for rate rule [Y_rad;Cdpri_Orad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 47,
    label = "[O][C]=C[O] + [O][C]=C[O] <=> OCCO + [O]C=C[O]",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.30102,'m^3/(mol*s)'), n=1.90834, Ea=(-4.74649,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [Y_rad;CH_d_Rrad]
    Euclidian distance = 0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using an average for rate rule [Y_rad;CH_d_Rrad]
Euclidian distance = 0
family: Disproportionation
""",
)

entry(
    index = 48,
    label = "O=[C]C=O + [O][C]=C[O] <=> OCCO(S) + [O]C=C[O]",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.48031e+06,'m^3/(mol*s)'), n=0, Ea=(25.104,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Y_rad;Cdpri_Rrad] for rate rule [Y_rad;Cdpri_Orad]
    Euclidian distance = 1.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [Y_rad;Cdpri_Rrad] for rate rule [Y_rad;Cdpri_Orad]
Euclidian distance = 1.0
family: Disproportionation
""",
)

entry(
    index = 49,
    label = "[O][C]=C[O] => O=[C]C=O",
    degeneracy = 1.0,
    duplicate = True,
    reversible = False,
    kinetics = Arrhenius(A=(1e+10,'s^-1'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [NOS]
    Euclidian distance = 0
    family: 1,2-Birad_to_alkene"""),
    longDesc = 
"""
Estimated using an average for rate rule [NOS]
Euclidian distance = 0
family: 1,2-Birad_to_alkene
""",
)

entry(
    index = 50,
    label = "[O][C]=C[O] <=> O=[C]C=O",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1.949e+11,'s^-1'), n=0.486, Ea=(22.8614,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [R2radExo;Y_rad;XH_Rrad]
    Euclidian distance = 0
    family: Intra_Disproportionation"""),
    longDesc = 
"""
Estimated using an average for rate rule [R2radExo;Y_rad;XH_Rrad]
Euclidian distance = 0
family: Intra_Disproportionation
""",
)

entry(
    index = 51,
    label = "O=[C]C=O <=> O=C1[CH]O1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.29014e+11,'s^-1'), n=0.514092, Ea=(189.777,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [R3_linear;multiplebond_intra;radadd_intra] for rate rule [R3_CO;carbonyl_intra_H;radadd_intra_CO]
    Euclidian distance = 2.449489742783178
    family: Intra_R_Add_Endocyclic"""),
    longDesc = 
"""
Estimated using template [R3_linear;multiplebond_intra;radadd_intra] for rate rule [R3_CO;carbonyl_intra_H;radadd_intra_CO]
Euclidian distance = 2.449489742783178
family: Intra_R_Add_Endocyclic
""",
)

entry(
    index = 52,
    label = "[O][C]=C[O] <=> O=C1[CH]O1",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.18e+16,'s^-1'), n=0, Ea=(2.9288,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [R3;Y_rad_out;Ypri_rad_out] for rate rule [R3_SD;O_rad;Ypri_rad_out]
    Euclidian distance = 1.4142135623730951
    family: Birad_recombination"""),
    longDesc = 
"""
Estimated using template [R3;Y_rad_out;Ypri_rad_out] for rate rule [R3_SD;O_rad;Ypri_rad_out]
Euclidian distance = 1.4142135623730951
family: Birad_recombination
""",
)

entry(
    index = 53,
    label = "O=C=CO <=> O=CC=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(605.045,'s^-1'), n=2.96, Ea=(143.867,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [R_ROR;R1_doublebond;R2_doublebond_H;R_O_H]
    Euclidian distance = 0
    family: ketoenol"""),
    longDesc = 
"""
Estimated using an average for rate rule [R_ROR;R1_doublebond;R2_doublebond_H;R_O_H]
Euclidian distance = 0
family: ketoenol
""",
)

entry(
    index = 54,
    label = "H + O=C=CO <=> H2 + O=[C]C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.4e+08,'cm^3/(mol*s)'), n=1.5, Ea=(27.6981,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""From training reaction 690 used for O/H/OneDeC;H_rad
    Exact match found for rate rule [O/H/OneDeC;H_rad]
    Euclidian distance = 0
    family: H_Abstraction"""),
    longDesc = 
"""
From training reaction 690 used for O/H/OneDeC;H_rad
Exact match found for rate rule [O/H/OneDeC;H_rad]
Euclidian distance = 0
family: H_Abstraction
""",
)

entry(
    index = 55,
    label = "H + O=[C]C=O <=> O=C=CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.80515e+06,'m^3/(mol*s)'), n=0.314888, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_N-3R!H->O',), comment="""BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_N-3R!H->O
        Total Standard Deviation in ln(k): 11.5401827615
    Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_N-3R!H->O]
    Euclidian distance = 0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_N-3R!H->O
    Total Standard Deviation in ln(k): 11.5401827615
Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_N-3R!H->O]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 56,
    label = "[CH]=O + O=[C]C=O <=> CO + O=C=CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.24e+23,'cm^3/(mol*s)'), n=-3.29, Ea=(142.497,'kJ/mol'), T0=(1,'K'), Tmin=(1140,'K'), Tmax=(1650,'K'), comment="""Estimated using template [O_sec_rad;HCO] for rate rule [O_rad/OneDe;HCO]
    Euclidian distance = 1.0
    family: CO_Disproportionation"""),
    longDesc = 
"""
Estimated using template [O_sec_rad;HCO] for rate rule [O_rad/OneDe;HCO]
Euclidian distance = 1.0
family: CO_Disproportionation
""",
)

entry(
    index = 57,
    label = "O=[C]C=O + O=C=CO <=> O=[C]C=O + O=CC=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.58273e-10,'m^3/(mol*s)'), n=4.66333, Ea=(172.883,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O_sec;CO_sec_rad] for rate rule [O/H/OneDeC;CO_rad/OneDe]
    Euclidian distance = 2.23606797749979
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [O_sec;CO_sec_rad] for rate rule [O/H/OneDeC;CO_rad/OneDe]
Euclidian distance = 2.23606797749979
family: H_Abstraction
""",
)

entry(
    index = 58,
    label = "O=[C]C=O + O=[C]C=O <=> OCCO(S) + O=C=CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(25.7788,'m^3/(mol*s)'), n=1.79333, Ea=(5.91252,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O_sec_rad;XH_s_Rrad] for rate rule [O_rad/OneDe;COpri_COrad]
    Euclidian distance = 2.23606797749979
    family: Disproportionation
    Ea raised from -4.5 to 5.9 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [O_sec_rad;XH_s_Rrad] for rate rule [O_rad/OneDe;COpri_COrad]
Euclidian distance = 2.23606797749979
family: Disproportionation
Ea raised from -4.5 to 5.9 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 59,
    label = "[CH]=O + O=C=CO <=> C=O + O=[C]C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.00543568,'m^3/(mol*s)'), n=2.7045, Ea=(21.8656,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O/H/OneDeC;Y_rad] for rate rule [O/H/OneDeC;CO_pri_rad]
    Euclidian distance = 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [O/H/OneDeC;Y_rad] for rate rule [O/H/OneDeC;CO_pri_rad]
Euclidian distance = 2.0
family: H_Abstraction
""",
)

entry(
    index = 60,
    label = "[O]C=C[O] <=> O=C=CO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.4874e+09,'s^-1'), n=1.045, Ea=(63.4002,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [R3radExo;Y_rad;XH_Rrad]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Intra_Disproportionation"""),
    longDesc = 
"""
Estimated using an average for rate rule [R3radExo;Y_rad;XH_Rrad]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Intra_Disproportionation
""",
)

entry(
    index = 61,
    label = "O=[C]C=O + [O]C=C[O] <=> O=[C]C=O + O=C=CO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(24935.6,'m^3/(mol*s)'), n=0.896667, Ea=(10.3205,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [O_rad;Cdpri_Rrad] + [O_sec_rad;XH_s_Rrad] for rate rule [O_rad/OneDe;Cdpri_Orad]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using average of templates [O_rad;Cdpri_Rrad] + [O_sec_rad;XH_s_Rrad] for rate rule [O_rad/OneDe;Cdpri_Orad]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 62,
    label = "[O][C]=C[O] + O=C=CO <=> O=[C]C=O + [O]C=C[O]",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.7e+08,'cm^3/(mol*s)'), n=1.5, Ea=(17.2799,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2000,'K'), comment="""Estimated using an average for rate rule [O/H/OneDeC;Y_1centerbirad]
    Euclidian distance = 0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using an average for rate rule [O/H/OneDeC;Y_1centerbirad]
Euclidian distance = 0
family: H_Abstraction
""",
)

entry(
    index = 63,
    label = "O=[C]C=O + [O][C]=C[O] <=> OCCO + O=C=CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(12467.8,'m^3/(mol*s)'), n=0.896667, Ea=(10.3205,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [O_rad;Cdpri_Rrad] + [O_sec_rad;XH_s_Rrad] for rate rule [O_rad/OneDe;Cdpri_Orad]
    Euclidian distance = 2.23606797749979
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using average of templates [O_rad;Cdpri_Rrad] + [O_sec_rad;XH_s_Rrad] for rate rule [O_rad/OneDe;Cdpri_Orad]
Euclidian distance = 2.23606797749979
family: Disproportionation
""",
)

entry(
    index = 64,
    label = "O=C=[C]O <=> O=[C]C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.9024e+09,'s^-1'), n=1.09833, Ea=(177.686,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [R2H_S;Cd_rad_out_double;XH_out] for rate rule [R2H_S;Cd_rad_out_double;O_H_out]
    Euclidian distance = 1.0
    family: intra_H_migration"""),
    longDesc = 
"""
Estimated using template [R2H_S;Cd_rad_out_double;XH_out] for rate rule [R2H_S;Cd_rad_out_double;O_H_out]
Euclidian distance = 1.0
family: intra_H_migration
""",
)

entry(
    index = 65,
    label = "H + OCCO <=> O=C=[C]O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(5.6103e+06,'m^3/(mol*s)'), n=0.314888, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_N-3R!H->O',), comment="""BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_N-3R!H->O
        Total Standard Deviation in ln(k): 11.5401827615
    Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_N-3R!H->O]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_N-3R!H->O
    Total Standard Deviation in ln(k): 11.5401827615
Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_N-Sp-3R!H=2CCNNOO_2CNO->O_N-3R!H->O]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 66,
    label = "[CH]=O + OCCO <=> CO + O=C=[C]O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2.48e+23,'cm^3/(mol*s)'), n=-3.29, Ea=(303.245,'kJ/mol'), T0=(1,'K'), Tmin=(1140,'K'), Tmax=(1650,'K'), comment="""Estimated using template [O_sec_rad;HCO] for rate rule [O_rad/OneDe;HCO]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: CO_Disproportionation"""),
    longDesc = 
"""
Estimated using template [O_sec_rad;HCO] for rate rule [O_rad/OneDe;HCO]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: CO_Disproportionation
""",
)

entry(
    index = 67,
    label = "OCCO + O=[C]C=O <=> OCCO(S) + O=C=[C]O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(51.5577,'m^3/(mol*s)'), n=1.79333, Ea=(168.029,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O_sec_rad;XH_s_Rrad] for rate rule [O_rad/OneDe;COpri_COrad]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Disproportionation
    Ea raised from -4.5 to 168.0 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [O_sec_rad;XH_s_Rrad] for rate rule [O_rad/OneDe;COpri_COrad]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
Ea raised from -4.5 to 168.0 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 68,
    label = "H + O=C=[C]O <=> H2 + OCCO(S)",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(97979.6,'m^3/(mol*s)'), n=0.75, Ea=(0.79496,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [H_rad;O_Rrad] for rate rule [H_rad;O_Cdrad]
    Euclidian distance = 1.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [H_rad;O_Rrad] for rate rule [H_rad;O_Cdrad]
Euclidian distance = 1.0
family: Disproportionation
""",
)

entry(
    index = 69,
    label = "H + OCCO(S) <=> O=C=[C]O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(2.37e+08,'cm^3/(mol*s)'), n=1.63, Ea=(30.7064,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1700,'K'), comment="""Estimated using template [Od_R;HJ] for rate rule [Od_Cdd;HJ]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Estimated using template [Od_R;HJ] for rate rule [Od_Cdd;HJ]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: R_Addition_MultipleBond
""",
)

entry(
    index = 70,
    label = "O=C=[C]O + O=[C]C=O <=> OCCO(S) + O=CC=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.81e+08,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CO_rad;O_Rrad] for rate rule [CO_rad/OneDe;O_Cdrad]
    Euclidian distance = 2.23606797749979
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [CO_rad;O_Rrad] for rate rule [CO_rad/OneDe;O_Cdrad]
Euclidian distance = 2.23606797749979
family: Disproportionation
""",
)

entry(
    index = 71,
    label = "OCCO + O=C=[C]O <=> OCCO(S) + O=[C]C=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(43158.4,'m^3/(mol*s)'), n=0.872005, Ea=(-0.430616,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Y_rad;O_Rrad] for rate rule [Y_rad;O_Cdrad]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [Y_rad;O_Rrad] for rate rule [Y_rad;O_Cdrad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 72,
    label = "[CH]=O + O=C=[C]O <=> C=O + OCCO(S)",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.81e+14,'cm^3/(mol*s)','*|/',3), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Estimated using template [CO_pri_rad;O_Rrad] for rate rule [CO_pri_rad;O_Cdrad]
    Euclidian distance = 1.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [CO_pri_rad;O_Rrad] for rate rule [CO_pri_rad;O_Cdrad]
Euclidian distance = 1.0
family: Disproportionation
""",
)

entry(
    index = 73,
    label = "OCCO + [O]C=C[O] <=> O=C=[C]O + O=[C]C=O",
    degeneracy = 4.0,
    kinetics = Arrhenius(A=(49871.3,'m^3/(mol*s)'), n=0.896667, Ea=(60.6667,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [O_rad;Cdpri_Rrad] + [O_sec_rad;XH_s_Rrad] for rate rule [O_rad/OneDe;Cdpri_Orad]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 4.0
    family: Disproportionation
    Ea raised from 60.5 to 60.7 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using average of templates [O_rad;Cdpri_Rrad] + [O_sec_rad;XH_s_Rrad] for rate rule [O_rad/OneDe;Cdpri_Orad]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 4.0
family: Disproportionation
Ea raised from 60.5 to 60.7 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 74,
    label = "O=C=[C]O + [O][C]=C[O] <=> OCCO(S) + [O]C=C[O]",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(21579.2,'m^3/(mol*s)'), n=0.872005, Ea=(-0.430616,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Y_rad;O_Rrad] for rate rule [Y_rad;O_Cdrad]
    Euclidian distance = 1.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [Y_rad;O_Rrad] for rate rule [Y_rad;O_Cdrad]
Euclidian distance = 1.0
family: Disproportionation
""",
)

entry(
    index = 75,
    label = "OCCO + [O][C]=C[O] <=> OCCO + O=C=[C]O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(24935.6,'m^3/(mol*s)'), n=0.896667, Ea=(10.3205,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [O_rad;Cdpri_Rrad] + [O_sec_rad;XH_s_Rrad] for rate rule [O_rad/OneDe;Cdpri_Orad]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using average of templates [O_rad;Cdpri_Rrad] + [O_sec_rad;XH_s_Rrad] for rate rule [O_rad/OneDe;Cdpri_Orad]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 76,
    label = "H + O=C=[C]O <=> O=C=CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.1386e+07,'m^3/(mol*s)'), n=0.308956, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=-1.11188672232, var=3.33851088254, Tref=1000.0, N=3, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_N-3R!H->O_Ext-3CS-R',), comment="""BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_N-3R!H->O_Ext-3CS-R
        Total Standard Deviation in ln(k): 6.45665544921
    Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_N-3R!H->O_Ext-3CS-R]
    Euclidian distance = 0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_N-3R!H->O_Ext-3CS-R
    Total Standard Deviation in ln(k): 6.45665544921
Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_N-3R!H->O_Ext-3CS-R]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 77,
    label = "[CH]=O + O=C=[C]O <=> CO + O=C=CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.033e+13,'cm^3/(mol*s)'), n=0, Ea=(26.7848,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Cd_rad;HCO] for rate rule [Cd_rad/NonDeO;HCO]
    Euclidian distance = 2.0
    family: CO_Disproportionation
    Ea raised from 0.0 to 26.8 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [Cd_rad;HCO] for rate rule [Cd_rad/NonDeO;HCO]
Euclidian distance = 2.0
family: CO_Disproportionation
Ea raised from 0.0 to 26.8 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 78,
    label = "H2 + O=C=[C]O <=> H + O=C=CO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(0.07496,'cm^3/(mol*s)'), n=3.944, Ea=(68.0109,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [H2;Cd_allenic_rad]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using an average for rate rule [H2;Cd_allenic_rad]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 79,
    label = "C=O + O=C=[C]O <=> [CH]=O + O=C=CO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(5420,'cm^3/(mol*s)','*|/',5), n=2.81, Ea=(24.5182,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""Estimated using template [CO_pri;Cd_rad] for rate rule [CO_pri;Cd_allenic_rad]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [CO_pri;Cd_rad] for rate rule [CO_pri;Cd_allenic_rad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 80,
    label = "O=C=[C]O + O=CC=O <=> O=[C]C=O + O=C=CO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(162600,'m^3/(mol*s)'), n=0, Ea=(15.3971,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CO_sec;Cd_rad] for rate rule [CO/H/OneDe;Cd_allenic_rad]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [CO_sec;Cd_rad] for rate rule [CO/H/OneDe;Cd_allenic_rad]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 81,
    label = "O=C=[C]O + [O]C=C[O] <=> O=[C]C=O + O=C=CO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(4.82e+06,'m^3/(mol*s)'), n=0, Ea=(25.104,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Cd_rad;Cdpri_Rrad] for rate rule [Cd_rad/NonDeO;Cdpri_Orad]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [Cd_rad;Cdpri_Rrad] for rate rule [Cd_rad/NonDeO;Cdpri_Orad]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 82,
    label = "O=C=[C]O + O=C=CO <=> O=[C]C=O + O=C=CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.00543568,'m^3/(mol*s)'), n=2.7045, Ea=(21.8656,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O/H/OneDeC;Y_rad] for rate rule [O/H/OneDeC;Cd_allenic_rad]
    Euclidian distance = 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [O/H/OneDeC;Y_rad] for rate rule [O/H/OneDeC;Cd_allenic_rad]
Euclidian distance = 2.0
family: H_Abstraction
""",
)

entry(
    index = 83,
    label = "O=C=[C]O + [O][C]=C[O] <=> OCCO + O=C=CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(6.45964e+06,'m^3/(mol*s)'), n=-0.14, Ea=(5.0208,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Cd_rad;XH_Rrad] for rate rule [Cd_rad/NonDeO;CH_d_Rrad]
    Euclidian distance = 2.8284271247461903
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [Cd_rad;XH_Rrad] for rate rule [Cd_rad/NonDeO;CH_d_Rrad]
Euclidian distance = 2.8284271247461903
family: Disproportionation
""",
)

entry(
    index = 84,
    label = "O=C=[C]O + O=C=[C]O <=> OCCO(S) + O=C=CO",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.01e+07,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Cd_rad;O_Rrad] for rate rule [Cd_rad/NonDeO;O_Cdrad]
    Euclidian distance = 2.23606797749979
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [Cd_rad;O_Rrad] for rate rule [Cd_rad/NonDeO;O_Cdrad]
Euclidian distance = 2.23606797749979
family: Disproportionation
""",
)

entry(
    index = 85,
    label = "O=C=[C]O + O=[C]C=O <=> OCCO(S) + O=C=CO",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(135.058,'m^3/(mol*s)'), n=1.56917, Ea=(-3.90507,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O_sec_rad;O_Rrad] for rate rule [O_rad/OneDe;O_Cdrad]
    Euclidian distance = 1.4142135623730951
    family: Disproportionation
    Ea raised from -3.9 to -3.9 kJ/mol."""),
    longDesc = 
"""
Estimated using template [O_sec_rad;O_Rrad] for rate rule [O_rad/OneDe;O_Cdrad]
Euclidian distance = 1.4142135623730951
family: Disproportionation
Ea raised from -3.9 to -3.9 kJ/mol.
""",
)

entry(
    index = 86,
    label = "O=C=[C]O + O=[C]C=O <=> OCCO(S) + O=C=CO",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(2.41e+06,'m^3/(mol*s)'), n=0, Ea=(25.104,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Cd_rad;Cdpri_Rrad] for rate rule [Cd_rad/NonDeO;Cdpri_Orad]
    Euclidian distance = 2.23606797749979
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [Cd_rad;Cdpri_Rrad] for rate rule [Cd_rad/NonDeO;Cdpri_Orad]
Euclidian distance = 2.23606797749979
family: Disproportionation
""",
)

entry(
    index = 87,
    label = "O=C=[C]O + [O]C=C[O] <=> [O][C]=C[O] + O=C=CO",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(0.000362364,'m^3/(mol*s)'), n=3.0654, Ea=(57.1822,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [X_H_or_Xrad_H_Xbirad_H_Xtrirad_H;Cd_allenic_rad] + [C_rad_H;Y_rad] for rate rule [C_rad_H;Cd_allenic_rad]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using average of templates [X_H_or_Xrad_H_Xbirad_H_Xtrirad_H;Cd_allenic_rad] + [C_rad_H;Y_rad] for rate rule [C_rad_H;Cd_allenic_rad]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 88,
    label = "O=C=[C]O + O=[C]C=O <=> OCCO(S) + O=C=CO",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(6.45964e+06,'m^3/(mol*s)'), n=-0.14, Ea=(5.0208,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [Cd_rad;XH_s_Rrad] for rate rule [Cd_rad/NonDeO;COpri_COrad]
    Euclidian distance = 2.8284271247461903
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [Cd_rad;XH_s_Rrad] for rate rule [Cd_rad/NonDeO;COpri_COrad]
Euclidian distance = 2.8284271247461903
family: Disproportionation
""",
)

entry(
    index = 89,
    label = "O=C=[C]O + O=[C]C=O <=> OCCO(S) + O=C=CO",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(135.058,'m^3/(mol*s)'), n=1.56917, Ea=(-3.90507,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O_sec_rad;O_Rrad] for rate rule [O_rad/OneDe;O_Cdrad]
    Euclidian distance = 1.4142135623730951
    family: Disproportionation
    Ea raised from -3.9 to -3.9 kJ/mol."""),
    longDesc = 
"""
Estimated using template [O_sec_rad;O_Rrad] for rate rule [O_rad/OneDe;O_Cdrad]
Euclidian distance = 1.4142135623730951
family: Disproportionation
Ea raised from -3.9 to -3.9 kJ/mol.
""",
)

entry(
    index = 90,
    label = "OCCO + O=C=[C]O <=> OCCO(S) + O=C=[C]O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(270.117,'m^3/(mol*s)'), n=1.56917, Ea=(54.1739,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [O_sec_rad;O_Rrad] for rate rule [O_rad/OneDe;O_Cdrad]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: Disproportionation
    Ea raised from -3.9 to -3.9 kJ/mol.
    Ea raised from -3.9 to 54.2 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [O_sec_rad;O_Rrad] for rate rule [O_rad/OneDe;O_Cdrad]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
Ea raised from -3.9 to -3.9 kJ/mol.
Ea raised from -3.9 to 54.2 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 91,
    label = "vacantX + [CH]=O <=> O=C[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.1, n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite]
    Euclidian distance = 0
    family: Surface_Adsorption_Single"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 92,
    label = "vacantX + vacantX + O=CC=O <=> O=C[Pt] + O=C[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(A=0.01, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 93,
    label = "vacantX + vacantX + C=O <=> [Pt] + O=C[Pt]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(A=0.02, n=0, Ea=(41.84,'kJ/mol'), T0=(1,'K'), Tmin=(200,'K'), Tmax=(3000,'K'), comment="""Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: Surface_Adsorption_Dissociative"""),
    longDesc = 
"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 94,
    label = "vacantX + O=C[Pt] <=> [Pt] + O=C=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(A=(3.71e+17,'m^2/(mol*s)'), n=0, Ea=(0,'J/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2000,'K'), comment="""Matched reaction 48 CXHO_1 + Ni_4 <=> OCX_3 + HX_5 in Surface_Dissociation/training
    This reaction matched rate rule [Combined;VacantSite]
    family: Surface_Dissociation
    metal: None"""),
    longDesc = 
"""
Matched reaction 48 CXHO_1 + Ni_4 <=> OCX_3 + HX_5 in Surface_Dissociation/training
This reaction matched rate rule [Combined;VacantSite]
family: Surface_Dissociation
metal: None
""",
)

entry(
    index = 95,
    label = "[CH]=O + O=[C]C=O <=> O=CC(=O)C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.81e+07,'m^3/(mol*s)'), n=-1.42812e-07, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, correlation='Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_3R!H->O_Ext-1C-R_N-5R!H->C',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_3R!H->O_Ext-1C-R_N-5R!H->C
        Total Standard Deviation in ln(k): 11.5401827615
    Exact match found for rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_3R!H->O_Ext-1C-R_N-5R!H->C]
    Euclidian distance = 0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_3R!H->O_Ext-1C-R_N-5R!H->C
    Total Standard Deviation in ln(k): 11.5401827615
Exact match found for rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_3R!H->O_Ext-1C-R_N-5R!H->C]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 96,
    label = "CO + O=[C]C=O <=> O=[C]C(=O)C=O",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1614.82,'m^3/(mol*s)'), n=0.595184, Ea=(5.28251,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [COm;Y_rad] for rate rule [COm;CO_sec_rad]
    Euclidian distance = 2.0
    family: R_Addition_COm"""),
    longDesc = 
"""
Estimated using template [COm;Y_rad] for rate rule [COm;CO_sec_rad]
Euclidian distance = 2.0
family: R_Addition_COm
""",
)

entry(
    index = 97,
    label = "CO + O=[C]C=O <=> O=[C]C(=O)C=O",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(0.0591985,'m^3/(mol*s)'), n=2.3675, Ea=(305.306,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [CO;R_H]
    Euclidian distance = 0
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Estimated using an average for rate rule [CO;R_H]
Euclidian distance = 0
family: 1,2_Insertion_CO
""",
)

entry(
    index = 98,
    label = "[CH]=O + OCCO <=> O=[C]C(=O)C=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.62e+07,'m^3/(mol*s)'), n=-1.42812e-07, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, correlation='Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_3R!H->O_Ext-1C-R_N-5R!H->C',), comment="""BM rule fitted to 2 training reactions at node Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_3R!H->O_Ext-1C-R_N-5R!H->C
        Total Standard Deviation in ln(k): 11.5401827615
    Exact match found for rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_3R!H->O_Ext-1C-R_N-5R!H->C]
    Euclidian distance = 0
    Multiplied by reaction path degeneracy 2.0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_3R!H->O_Ext-1C-R_N-5R!H->C
    Total Standard Deviation in ln(k): 11.5401827615
Exact match found for rate rule [Root_N-1R->H_N-1CNOS->N_N-1COS->O_1CS->C_N-1C-inRing_Ext-2R-R_Ext-2R-R_3R!H->O_Ext-1C-R_N-5R!H->C]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: R_Recombination
""",
)

entry(
    index = 99,
    label = "[CH]=O + OCCO(S) <=> O=[C]C(=O)C=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.04e+12,'cm^3/(mol*s)'), n=0, Ea=(93.9308,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Estimated using template [Cd_R;CO_pri_rad] for rate rule [Ck_O;CO_pri_rad]
    Euclidian distance = 2.0
    Multiplied by reaction path degeneracy 2.0
    family: R_Addition_MultipleBond"""),
    longDesc = 
"""
Estimated using template [Cd_R;CO_pri_rad] for rate rule [Ck_O;CO_pri_rad]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: R_Addition_MultipleBond
""",
)

entry(
    index = 100,
    label = "H + O=[C]C(=O)C=O <=> O=CC(=O)C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.10287e+13,'m^3/(mol*s)'), n=-2.74437, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), uncertainty=RateUncertainty(mu=0.0, var=33.1368631905, Tref=1000.0, N=1, correlation='Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O',), comment="""BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O
        Total Standard Deviation in ln(k): 11.5401827615
    Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O]
    Euclidian distance = 0
    family: R_Recombination"""),
    longDesc = 
"""
BM rule fitted to 2 training reactions at node Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O
    Total Standard Deviation in ln(k): 11.5401827615
Exact match found for rate rule [Root_1R->H_N-2R->S_N-2CHNO->H_N-2CNO-inRing_Ext-2CNO-R_Sp-3R!H=2CCNNOO_3R!H->O]
Euclidian distance = 0
family: R_Recombination
""",
)

entry(
    index = 101,
    label = "[CH]=O + O=[C]C(=O)C=O <=> CO + O=CC(=O)C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.8e+13,'cm^3/(mol*s)','+|-',9e+12), n=0, Ea=(153.377,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CO_rad;HCO] for rate rule [CO_rad/OneDe;HCO]
    Euclidian distance = 2.0
    family: CO_Disproportionation
    Ea raised from 0.0 to 153.4 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [CO_rad;HCO] for rate rule [CO_rad/OneDe;HCO]
Euclidian distance = 2.0
family: CO_Disproportionation
Ea raised from 0.0 to 153.4 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 102,
    label = "H + O=CC(=O)C=O <=> H2 + O=[C]C(=O)C=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(260000,'cm^3/(mol*s)'), n=2.58, Ea=(5.1003,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CO_sec;H_rad] for rate rule [CO/H/OneDe;H_rad]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [CO_sec;H_rad] for rate rule [CO/H/OneDe;H_rad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 103,
    label = "[CH]=O + O=CC(=O)C=O <=> C=O + O=[C]C(=O)C=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1940.76,'m^3/(mol*s)'), n=0.871895, Ea=(42.7867,'kJ/mol'), T0=(1,'K'), comment="""Estimated using average of templates [CO_H;CO_rad] + [CO_sec;Y_rad] for rate rule [CO/H/OneDe;CO_pri_rad]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using average of templates [CO_H;CO_rad] + [CO_sec;Y_rad] for rate rule [CO/H/OneDe;CO_pri_rad]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 104,
    label = "O=[C]C=O + O=CC(=O)C=O <=> O=CC=O + O=[C]C(=O)C=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(181000,'m^3/(mol*s)'), n=0, Ea=(54.0573,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CO_H;CO_sec_rad] for rate rule [CO/H/OneDe;CO_rad/OneDe]
    Euclidian distance = 2.23606797749979
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [CO_H;CO_sec_rad] for rate rule [CO/H/OneDe;CO_rad/OneDe]
Euclidian distance = 2.23606797749979
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 105,
    label = "[O]C=C[O] + O=[C]C(=O)C=O <=> O=[C]C=O + O=CC(=O)C=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(3.62e+08,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CO_rad;XH_s_Rrad] for rate rule [CO_rad/OneDe;Cdpri_Orad]
    Euclidian distance = 2.8284271247461903
    Multiplied by reaction path degeneracy 2.0
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [CO_rad;XH_s_Rrad] for rate rule [CO_rad/OneDe;Cdpri_Orad]
Euclidian distance = 2.8284271247461903
Multiplied by reaction path degeneracy 2.0
family: Disproportionation
""",
)

entry(
    index = 106,
    label = "O=[C]C=O + O=CC(=O)C=O <=> O=C=CO + O=[C]C(=O)C=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(7.1e-14,'m^3/(mol*s)'), n=5.64, Ea=(38.5807,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CO_H;O_rad/OneDe] for rate rule [CO/H/OneDe;O_rad/Cd]
    Euclidian distance = 2.8284271247461903
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [CO_H;O_rad/OneDe] for rate rule [CO/H/OneDe;O_rad/Cd]
Euclidian distance = 2.8284271247461903
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 107,
    label = "[O][C]=C[O] + O=[C]C(=O)C=O <=> OCCO + O=CC(=O)C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.81e+08,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CO_rad;XH_Rrad] for rate rule [CO_rad/OneDe;CH_d_Rrad]
    Euclidian distance = 2.8284271247461903
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [CO_rad;XH_Rrad] for rate rule [CO_rad/OneDe;CH_d_Rrad]
Euclidian distance = 2.8284271247461903
family: Disproportionation
""",
)

entry(
    index = 108,
    label = "O=C=[C]O + O=[C]C(=O)C=O <=> OCCO(S) + O=CC(=O)C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.81e+08,'m^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CO_rad;O_Rrad] for rate rule [CO_rad/OneDe;O_Cdrad]
    Euclidian distance = 2.23606797749979
    family: Disproportionation"""),
    longDesc = 
"""
Estimated using template [CO_rad;O_Rrad] for rate rule [CO_rad/OneDe;O_Cdrad]
Euclidian distance = 2.23606797749979
family: Disproportionation
""",
)

entry(
    index = 109,
    label = "O=[C]C=O + O=[C]C(=O)C=O <=> OCCO(S) + O=CC(=O)C=O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.81e+08,'m^3/(mol*s)'), n=0, Ea=(18.6498,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CO_rad;XH_s_Rrad] for rate rule [CO_rad/OneDe;Cdpri_Orad]
    Euclidian distance = 2.8284271247461903
    family: Disproportionation
    Ea raised from 0.0 to 18.6 kJ/mol to match endothermicity of reaction."""),
    longDesc = 
"""
Estimated using template [CO_rad;XH_s_Rrad] for rate rule [CO_rad/OneDe;Cdpri_Orad]
Euclidian distance = 2.8284271247461903
family: Disproportionation
Ea raised from 0.0 to 18.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 110,
    label = "[O][C]=C[O] + O=CC(=O)C=O <=> [O]C=C[O] + O=[C]C(=O)C=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(1.16e+07,'m^3/(mol*s)'), n=0, Ea=(7.56467,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CO_sec;Y_1centerbirad] for rate rule [CO/H/OneDe;Y_1centerbirad]
    Euclidian distance = 1.0
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [CO_sec;Y_1centerbirad] for rate rule [CO/H/OneDe;Y_1centerbirad]
Euclidian distance = 1.0
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 111,
    label = "O=C=[C]O + O=CC(=O)C=O <=> O=C=CO + O=[C]C(=O)C=O",
    degeneracy = 2.0,
    kinetics = Arrhenius(A=(162600,'m^3/(mol*s)'), n=0, Ea=(15.3971,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [CO_sec;Cd_rad] for rate rule [CO/H/OneDe;Cd_allenic_rad]
    Euclidian distance = 1.4142135623730951
    Multiplied by reaction path degeneracy 2.0
    family: H_Abstraction"""),
    longDesc = 
"""
Estimated using template [CO_sec;Cd_rad] for rate rule [CO/H/OneDe;Cd_allenic_rad]
Euclidian distance = 1.4142135623730951
Multiplied by reaction path degeneracy 2.0
family: H_Abstraction
""",
)

entry(
    index = 112,
    label = "CO + O=[C]C=O <=> O=[C]C(=O)C=O",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(1614.82,'m^3/(mol*s)'), n=0.595184, Ea=(5.28251,'kJ/mol'), T0=(1,'K'), comment="""Estimated using template [COm;Y_rad] for rate rule [COm;CO_sec_rad]
    Euclidian distance = 2.0
    family: R_Addition_COm"""),
    longDesc = 
"""
Estimated using template [COm;Y_rad] for rate rule [COm;CO_sec_rad]
Euclidian distance = 2.0
family: R_Addition_COm
""",
)

entry(
    index = 113,
    label = "CO + O=[C]C=O <=> O=[C]C(=O)C=O",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = Arrhenius(A=(0.0591985,'m^3/(mol*s)'), n=2.3675, Ea=(305.306,'kJ/mol'), T0=(1,'K'), comment="""Estimated using an average for rate rule [CO;R_H]
    Euclidian distance = 0
    family: 1,2_Insertion_CO"""),
    longDesc = 
"""
Estimated using an average for rate rule [CO;R_H]
Euclidian distance = 0
family: 1,2_Insertion_CO
""",
)

